name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

env:
  DOTNET_VERSION: '9.0.x'  # Use .NET 9 (stable)
  CONFIGURATION: 'Release'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for OIDC token
      contents: write  # Required for creating releases
      packages: write  # Required for publishing packages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for GitVersioning

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore --verbosity minimal

    - name: Pack NuGet package
      run: dotnet pack ThousandEyes.Api/ThousandEyes.Api.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output ./artifacts

    - name: Upload NuGet package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg

    - name: Upload Symbol package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: symbol-packages
        path: ./artifacts/*.snupkg

    - name: Publish to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish symbols to NuGet.org
      run: dotnet nuget push ./artifacts/*.snupkg --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this release

          ### Features
          - See commit history for detailed changes

          ### NuGet Package
          This release is available on NuGet.org as `ThousandEyes.Api` version ${{ github.ref_name }}

          ```bash
          dotnet add package ThousandEyes.Api --version ${{ github.ref_name }}
          ```

          ### Installation
          ```csharp
          using ThousandEyes.Api;

          var client = new ThousandEyesClient(new ThousandEyesClientOptions
          {
              BearerToken = "your-bearer-token-here"
          });

          // Account Management
          var users = await client.AccountManagement.Users.GetAllAsync(aid: null, cancellationToken);
          var currentUser = await client.AccountManagement.Users.GetCurrentAsync(cancellationToken);

          // Tests Management
          var tests = await client.Tests.Tests.GetAllAsync(aid: null, cancellationToken);
          var httpTests = await client.Tests.HttpServerTests.GetAllAsync(aid: null, cancellationToken);

          // Agents Management
          var agents = await client.Agents.Agents.GetAllAsync(aid: null, cancellationToken);

          // Test Results
          var results = await client.TestResults.TestResults.GetNetworkResultsAsync(
              testId: "12345",
              fromDate: DateTime.UtcNow.AddHours(-24),
              toDate: DateTime.UtcNow,
              aid: null,
              cancellationToken);
          ```

          ### Download
          - **NuGet Package**: Available on [NuGet.org](https://www.nuget.org/packages/ThousandEyes.Api/)
          - **Symbol Package**: Debugging symbols included for enhanced development experience
        files: |
          ./artifacts/*.nupkg
          ./artifacts/*.snupkg
        draft: false
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}